HW04: Grep
kibrq/sd-practice pull request #19
Opened 2022-02-16 21:07 UTC by maxuh14

2022-02-22 11:08 UTC, yurii-litvinov requested changes
По диаграмме:
- там есть куча вещей, которые UML не умеет:
  - Unit
  - лямбдообразный способ записи операций (причём вроде как низачем, там везде обычные методы)
  - "Uses specified grammar" и прочие отчёркнутые пунктиром комментарии внутри класса
- стрелки ассоциаций неправильные, они рисуются так: https://www.uml-diagrams.org/association.html?context=class-diagrams. У вас же стрелки на концах жирнее, чем положено :)
- Expression Handler включает в себя Statement Handler, и Statement Handler включает в себя Expression Handler? Судя по коду, первое правда, второе нет.
- Чисто визуально лучше рисовать генерализацию/реализацию интерфейсов сверху вниз, это делает диаграмму более читаемой.

2022-02-22 11:08 UTC, yurii-litvinov commented on src/test/kotlin/ru/hse/shell/command/GrepTest.kt
> +    )
Я бы ещё плохие случаи рассмотрел, типа `grep -A trololo` и т.п.

2022-02-23 10:31 UTC, yurii-litvinov approved these changes
На диаграмме Unit местами так и остался, и я бы ещё ExitCode нарисовал как enum, но стало гораздо лучше. Зачтена.

2022-02-23 10:31 UTC, yurii-litvinov commented on src/test/kotlin/ru/hse/shell/command/GrepTest.kt
> +        Assertions.assertThrows(Exception::class.java) {
Проверять, что кидается просто какое-то исключение — как-то неспецифично. Вы ведь в каждом случае знаете, какое именно исключение будет кидаться.

2022-02-23 13:15 UTC, maxuh14 commented
fixed

2022-02-23 13:15 UTC, closed without merging