Hw01
kibrq/sd-practice pull request #2
Opened 2022-01-23 16:33 UTC by maxuh14

Выполнили:
Суходольский Максим
Бриллиантов Кирилл
Салькаев Руслан

2022-01-23 18:04 UTC, yurii-litvinov requested changes

2022-01-23 18:04 UTC, yurii-litvinov commented on hw01/README.md
> +## Грамматика
Стоит начинать архитектурное описание с "высоты птичьего полёта" — как вообще устроена система, из каких крупных блоков состоит, как передаётся управление и данные. Грамматика — это скорее деталь реализации, я бы её куда-нибудь ближе к концу поместил.

2022-01-23 18:04 UTC, yurii-litvinov commented on hw01/README.md
> +<img src="grammar.png">
👍 
(грамматика хороша, но вставлять листинг как картинку — не очень)

2022-01-23 18:04 UTC, yurii-litvinov commented on hw01/README.md
> +* `St` — команда либо присваивание.
Стоит нетерминалы более мнемонично называть. St — это, наверное, Statement или что-то такое?

2022-01-23 18:04 UTC, yurii-litvinov commented on hw01/README.md
> +* `EvalString` — строка без пробелов, в которой учитываются одинарные и двойные кавычки и операции с `$`. Второе можно вычислить, подставив вместо `$x` значение `x` или вычислив значение внутри `$(..
`$(...)` не просили, и аккуратная его реализация может принести неожиданные трудности, так что не надо. Лучше убрать.

2022-01-23 18:04 UTC, yurii-litvinov commented on hw01/README.md
> +`Eq` имеет смысл `Assignment`, но второе сложно осмысленно сократить до двух букв.
А надо? :)

2022-01-23 18:04 UTC, yurii-litvinov commented on hw01/README.md
> +Также в начале создается экземпляр `Environment`, который является оберткой над `Map<String, String>`. Это окружение нашей программы. Стоит отметить, что башевские переменные независимы от наших, и ч
"башевские переменные" я бы назвал "переменные среды", а то никто ведь не сказал, что этот шелл будет запускаться под bash-ем.

2022-01-23 18:04 UTC, yurii-litvinov commented on hw01/README.md
> +Для второй фазы: она сначала вычисляет все `EvalString` внутри `Statement`, используя `Env` и формальное описание грамматики:
Тут может быть уже поздно — может не получиться реализовать пример со слайдов:
```
x=ex
y=it
$x$y
```
Как я понял, у вас оно исполнится как команда `ex` с аргументом `it`, а судя по примеру, хочется именно `exit` (кстати, у коллег прошлых лет вызывало конфуз то, что в дистрибутивах Linux обычно есть программа ex, она на этом тесте честно запускалась как внешний процесс и ничего не работало). 

Для шелла это весьма критично, потому что такая сематника часто используется для сборки строк типа image01, image02 и т.п.

2022-01-23 18:04 UTC, yurii-litvinov commented on hw01/README.md
> +Вычислив все `EvalString`, внутри `St` не остается вычислений с помощью `$`.
То есть подстановка выполняется, пока можно? А вот на паре кто-то приводил пример с `x=$x`, у вас на нём не сломается?

2022-01-23 18:04 UTC, yurii-litvinov commented on hw01/README.md
> +Таким образом, распознавание команды выглядит как `map[args.first()]`.
Это и абстрактный класс для всех команд, и фабрика команд, и реестр команд, куда наследники (которых непонятно кто создаёт) в момент создания (а что будет, если создать exit дважды?) дописывает свой экземпляр (который также является AbstractCommand, так что у него тоже есть мапа, и в неё тоже теоретически можно вписаться). Ну, я говорил, что овердизайн приветствуется, но мне кажется, что вы сотворили монстра :)

Думаю, что AbstractCommand могла бы быть чем-то вроде CommandRepository, где просто лежит мапа, инициализирующаяся в конструкторе (можно даже извратиться и в конструкторе рефлексией обходить доступные классы, ища в них классы с суффиксом Command, и добавлять в мапу автоматически, но в общем случае это плохая идея). А AbstractCommand в таком случае могла бы стать интерфейсом Command, с методом perform, и уже его бы реализовывали настоящие команды.

2022-01-23 18:04 UTC, yurii-litvinov commented on hw01/README.md
> +  - Минусы: не круто, что какая-то логика работы завязана на исключеняих (не обработка ошибок)
Угу

2022-01-23 18:04 UTC, yurii-litvinov commented on hw01/README.md
> +  - Минусы: придется писать много (может и не много) ифов и не хочется заводить флаги ради одной команды `exit`
Флаг мог бы быть частью состояния шелла. У вас уже есть Env (который, вообще говоря, нужен для вызова внешней команды, чтобы ей передать окружение. Хотя вы и говорите, что у вас переменные среды и ваши переменные независимы, для пользователя может быть неожиданно, что внешний процесс к ним доступа не имеет). Ещё в будущем может появиться pwd, и тогда булевый флажок "Пора выходить" в классе "Состояние шелла" будет не таким страшным.

2022-01-23 18:04 UTC, yurii-litvinov commented on hw01/README.md
> +Комментарий про многопоточность: в пайплайне можно выделить независимые части, который можно выполнять параллельно. Это требует анализа выполнения самой команды:  на первый взгляд важно читает ли она
Ну, в реализации лучше всё-таки всё последовательно исполнять, иначе запутаетесь. Тем более что так сложно — тут в плане чтения из предыдущей команды нужен асинхронный ввод-вывод, типа очереди сообщений.

2022-01-23 18:04 UTC, yurii-litvinov commented on hw01/README.md
> +В методe `call` происходит распознавание: если такой команды нет, то вызывается внешняя. Метод `perform` является абстрактным, его должны переопределить наследники. Наследниками данного класса являют
Код возврата, кстати, стоит заранее предусмотреть, хотя пока его никак не использовать (разве что можно заканчивать исполнение пайпа, если он не 0)

2022-01-26 13:35 UTC, maxuh14 commented on hw01/README.md
> +<img src="grammar.png">
В листинге не смог выделить цветом символы, имеющее буквальное значение -- если знаете как, подскажите. Поэтому картинкой казалось понятнее.

2022-01-26 13:35 UTC, maxuh14 commented on hw01/README.md
> +* `St` — команда либо присваивание.
Переименовал.

2022-01-26 13:38 UTC, chimbersaw commented on hw01/README.md
> +* `EvalString` — строка без пробелов, в которой учитываются одинарные и двойные кавычки и операции с `$`. Второе можно вычислить, подставив вместо `$x` значение `x` или вычислив значение внутри `$(..
ok

2022-01-26 13:49 UTC, maxuh14 commented on hw01/README.md
> +Комментарий про многопоточность: в пайплайне можно выделить независимые части, который можно выполнять параллельно. Это требует анализа выполнения самой команды:  на первый взгляд важно читает ли она
Реализовывать будем последовательно, этот комментарий на подумать, на будущее.

2022-01-26 13:54 UTC, maxuh14 commented on hw01/README.md
> +Для второй фазы: она сначала вычисляет все `EvalString` внутри `Statement`, используя `Env` и формальное описание грамматики:
У нас все должно быть норм: этот `Statement` парсится как `Command`, который парсится сначала в единственный `EvalString`(по нашей грамматике команда с аргументами -- `EvalString`-и только через `\s+`). Этот `EvalString` уже парсится в два `$Id`, и подстановка в этом месте правильно их подстановит и "склеит".

2022-01-26 13:58 UTC, maxuh14 commented on hw01/README.md
> +Вычислив все `EvalString`, внутри `St` не остается вычислений с помощью `$`.
Пусть `x=239`.
Подстановка делается до выполнения самого `Statement`, то есть сначала `$x` заменится на `239`(и произведутся любые другие подстановки с `$`(они не меняют контекст)), а только потом выполнится сама команда `x=239`(в итоге ничего не поменяется, как и ожидается).

2022-01-26 14:19 UTC, chimbersaw commented on hw01/README.md
> +  - Минусы: придется писать много (может и не много) ифов и не хочется заводить флаги ради одной команды `exit`
Хорошая идея, флаг будет хранится в `Env`, исправил.

2022-01-26 14:22 UTC, maxuh14 commented on hw01/README.md
> +В методe `call` происходит распознавание: если такой команды нет, то вызывается внешняя. Метод `perform` является абстрактным, его должны переопределить наследники. Наследниками данного класса являют
Ок, пусть будет передаваться сущность `IO`, в которой будет и `Input`, и `Output`, а `perform` команды будет возвращать `exit code`.

2022-01-26 14:47 UTC, maxuh14 commented on hw01/README.md
> +Таким образом, распознавание команды выглядит как `map[args.first()]`.
Ок, отобразил на схеме и в описании.

2022-01-27 11:10 UTC, yurii-litvinov requested changes
Почти всё хорошо, но пару моментов ещё стоит уточнить, иначе при реализации могут быть сюрпризы.

2022-01-27 11:10 UTC, yurii-litvinov commented on hw01/README.md
> +Для второй фазы: она сначала вычисляет все `EvalString` внутри `Statement`, используя `Env` и формальное описание грамматики:
И правда. Но тогда наоборот,
```
x="echo 123"
$x
```
В bash выведет 123, у вас --- "неизвестная команда". Правда, у вас судя по грамматике EvalString не может иметь пробелы, а поскольку EvalString -> "EvalString", то и внутри кавычек не может быть пробелов. Надеюсь, что это всё-таки не так задумывалось.

В принципе, это допустимо (говорят, zsh ведёт себя именно так), но стоит это явно задокументировать.

2022-01-27 11:10 UTC, yurii-litvinov commented on hw01/README.md
> +Реализуют этот интерфейс классы-команды `CatCommand`, `EchoCommand`, `WcCommand`, `PwdCommand`, `ExitCommand`, а также `ExternalCommand`, которая пытается исполнить внешнюю команду(не нашли -- исключ
Про внешние команды стоило всё-таки написать про переменные окружения. И как поиск выполняется. 

Кстати, не уверен, что "не нашли" стоит именно исключением обрабатывать — это ошибка пользователя. С одной стороны это ошибка, так что исключение ок, с другой стороны пользователю свойственно ошибаться, так что ситуация вовсе не исключительная. С технической точки зрения, возможно, стоит различать запуск внешней команды, которая вернула ненулевой код, и незапуск, так что исключение оправданно, но идеологически от пользователя нельзя ожидать всегда корректного ввода.

2022-01-27 11:11 UTC, yurii-litvinov commented on hw01/README.md
> +<img src="grammar.png">
Я бы грамматику оформил просто текстом, выделив литералы, например, жирным. Листинг через ``` действительно выделять не умеет вроде

2022-01-27 11:14 UTC, yurii-litvinov commented on hw01/README.md
> +Вычислив все `EvalString`, внутри `St` не остается вычислений с помощью `$`.
А поскольку эскейпить `$` нельзя (разве что, как я понял, `x='$x'` у вас подставится прямо с кавычками), после подстановки никогда не может получиться строка с `$`, где требуется ещё замена. Тогда да, скорее всего, у вас проблем не будет. Окей, можно так.

2022-01-29 16:30 UTC, maxuh14 commented on hw01/README.md
> +Реализуют этот интерфейс классы-команды `CatCommand`, `EchoCommand`, `WcCommand`, `PwdCommand`, `ExitCommand`, а также `ExternalCommand`, которая пытается исполнить внешнюю команду(не нашли -- исключ
Написал про запуск внешних команд и передачу env.
Насчет исключения: действительно различать команду, возвращающую ненулевой код, полезно.
Также сам `Process` кидает исключение, если команда не нашлась, поэтому кажется логичным хендлить это именно исключением.

2022-01-29 16:35 UTC, maxuh14 commented on hw01/README.md
> +Для второй фазы: она сначала вычисляет все `EvalString` внутри `Statement`, используя `Env` и формальное описание грамматики:
Выделили DoubleQuotes, исправив, что внутри могут быть пробелы.
Написали новый алгоритм избавления от кавычек и парсинга команды: до этого мы неправильно понимали, как баш подставляет `$`, сейчас вроде все поняли. Пример выше работает как в баше(выводит 123).

2022-01-29 17:09 UTC, yurii-litvinov commented on hw01/README.md
> +Реализуют этот интерфейс классы-команды `CatCommand`, `EchoCommand`, `WcCommand`, `PwdCommand`, `ExitCommand`, а также `ExternalCommand`, которая пытается исполнить внешнюю команду(не нашли -- исключ
Ага, разумно

2022-01-29 17:10 UTC, yurii-litvinov approved these changes
Да, теперь всё ок, зачтена

2022-02-03 15:46 UTC, merged