HW07: Roguelike implementation pt.1
kibrq/sd-practice pull request #22
Opened 2022-04-11 00:52 UTC by maxuh14

2022-04-16 09:15 UTC, uncerso requested changes
А где инструкция по сборке, запуску тестов, а также всякие полезные сведения, как, например, управление? Напишите нормальный readme.

2022-04-17 23:48 UTC, maxuh14 commented
> А где инструкция по сборке, запуску тестов, а также всякие полезные сведения, как, например, управление? Напишите нормальный readme.

Написал

2022-05-16 20:27 UTC, uncerso reviewed
Мало как-то комментариев. Ладно методы, вы неплохие им имена дали, так что можно простить, но вот к классам нужно кратенькое описание, что это за звери.

2022-05-16 20:27 UTC, uncerso commented on README.md
> +./gradlew test
Тесты должны показывать как минимум сколько тестов запустилось, сколько прошли, сколько упали.

2022-05-16 20:27 UTC, uncerso commented on src/main/kotlin/ru/hse/xcv/model/entities/Hero.kt
> +        // https://www.youtube.com/watch?v=zTbw-ln-Fb4
Нет 10 часовой версии :(

2022-05-16 20:27 UTC, uncerso commented on src/main/kotlin/ru/hse/xcv/model/entities/Mob.kt
> +                else -> throw IllegalStateException()
Лучше assert.

Исключения -- для плохих, редких, но возможных случаев. 

assert -- для невозможных.

2022-05-16 20:27 UTC, uncerso commented on src/main/kotlin/ru/hse/xcv/util/InputManager.kt
> + * Very complicated logic for smooth movement.
Странное какое-то описание.

2022-05-16 20:27 UTC, uncerso commented on src/main/kotlin/ru/hse/xcv/mapgen/RandomPatternFieldGenerationStrategy.kt
> +    override fun generate(): FieldModel {
Много всякой логики в одном методе. Разбейте на несколько с хорошими именами.

2022-05-16 20:27 UTC, uncerso commented on src/main/kotlin/ru/hse/xcv/events/Event.kt
> +    val offset: Position,
offset от чего?

2022-05-16 21:13 UTC, maxuh14 commented on README.md
> +./gradlew test
Есть уже в следующем PR, могу и сюда перенести

2022-05-16 21:15 UTC, maxuh14 commented on src/main/kotlin/ru/hse/xcv/model/entities/Mob.kt
> +                else -> throw IllegalStateException()
Согласился. В будущем PR сделано без `when`, через `.random()`

2022-05-16 21:18 UTC, maxuh14 commented on src/main/kotlin/ru/hse/xcv/util/InputManager.kt
> + * Very complicated logic for smooth movement.
Очень долго пытался добиться идеального, как по мне, инпута(можно двигаться с зажатыми клавишами, можно тыкать одиночными, но при этом если два раза успеть тыкнуть, то точно подвинешься на 2 клетки, но если заспамить много раз то не будет двигаться после отжатия кнопок и тд тп). Поэтому сама логика получилось действительно странная, и её очень сложно нормально описать, кроме как `Very complicated`

2022-05-16 21:32 UTC, maxuh14 commented on src/main/kotlin/ru/hse/xcv/events/Event.kt
> +    val offset: Position,
От текущего положения

2022-06-04 19:38 UTC, maxuh14 commented on src/main/kotlin/ru/hse/xcv/mapgen/RandomPatternFieldGenerationStrategy.kt
> +    override fun generate(): FieldModel {
Исправил

2022-06-04 19:38 UTC, maxuh14 commented
@uncerso

2022-06-04 22:44 UTC, uncerso approved these changes

2022-06-04 22:44 UTC, uncerso commented on src/main/kotlin/ru/hse/xcv/mapgen/RandomPatternFieldGenerationStrategy.kt
> +            }.randomOrNull()?.let {
Код должен сам описывать, что он делает. Если вам хочется внутри функции оставить комментарий, то должна быть очень веская причина (например, лютые требования производительности заставляют написать битовую магию, или же за парой строк лежит безумная математика, без которой ничего непонятно). Без такой веской причины вы делаете что-то неправильно, и стоит как минимум вынести этот кусок кода в отдельную функцию, сделав вместо комментария хорошее название для этой функции.

В данном случае вам ничего не мешает сделать функции `createHero` и `areNoMobsNearby`. И вот уже комментарии не нужны.

2022-06-05 00:46 UTC, closed without merging