HW11: Hwproj architecture
kibrq/sd-practice pull request #36
Opened 2022-05-13 20:59 UTC by maxuh14

Выполнили:
Суходольский Максим
Бриллиантов Кирилл
Салькаев Руслан

2022-06-16 15:35 UTC, yurii-litvinov requested changes

2022-06-16 15:35 UTC, yurii-litvinov commented on description/ARCHITECTURE.md
> +# Описание системы
По-хорошему, надо начать с общего описания системы: требований, сценариев использования (тут было бы очень кстати расписать устройство UI и переходы между экранами —  важная часть архитектуры, про которую часто забывают) и т.п.

2022-06-16 15:35 UTC, yurii-litvinov commented on description/ARCHITECTURE.md
> +- API. Данный компонент содержит логику обработки запросов от пользователей. Классы-контроллеры, которые слуюшают REST-Endpoint'ы, и классы-сервисы, которые управляют потоком данных.
```suggestion
- API. Данный компонент содержит логику обработки запросов от пользователей. Классы-контроллеры, которые слушают REST-Endpoint'ы, и классы-сервисы, которые управляют потоком данных.
```

2022-06-16 15:35 UTC, yurii-litvinov commented on description/ARCHITECTURE.md
> +![Class diagram](diagrams/img/class-diagram.drawio.svg)
- Не надо дублировать ассоциации полями
- У CheckerVerdict стрелка не в ту сторону, да и вообще она не нужна

2022-06-16 15:35 UTC, yurii-litvinov commented on description/ARCHITECTURE.md
> +  - `submissions/view`. Просмотреть все. Возвращает список всех попыток.
`/view` — это не по REST как-то. Выглядит как действие, а не запрос к коллекции

2022-06-16 15:35 UTC, yurii-litvinov commented on description/ARCHITECTURE.md
> +  - `submissions/{submissionId}`. Просмотреть конкретную. Возвращает детальную информацию о попытки с номером `submissionId`.
```suggestion
  - `submissions/{submissionId}`. Просмотреть конкретную. Возвращает детальную информацию о попытке с номером `submissionId`.
```

2022-06-16 15:35 UTC, yurii-litvinov commented on description/ARCHITECTURE.md
> +  - `/teacher/uploadChecker`. Позволяет загрузить чекер преподу. Тело: json, представлюящим Dockerfile. Этот Dockerfile вместе с генерированным название кладется в базу, и создается event на создание
Тоже, действие, а не ресурс

2022-06-16 15:35 UTC, yurii-litvinov commented on description/ARCHITECTURE.md
> +  - `/student/uploadSubmission`. Позвоялет загрузить чекер преподавателю. Тело: json, представляющим ссылку на гитхаб. Создается новая попытка и кладется в базу, также создается event на проверку реш
Ну вряд ли "чекер преподавателю"

2022-06-16 15:35 UTC, yurii-litvinov commented on description/ARCHITECTURE.md
> +  - `/student/uploadSubmission`. Позвоялет загрузить чекер преподавателю. Тело: json, представляющим ссылку на гитхаб. Создается новая попытка и кладется в базу, также создается event на проверку реш
```suggestion
  - `/student/uploadSubmission`. Позвоялет загрузить чекер преподавателю. Тело: json, содержащий ссылку на гитхаб. Создается новая попытка и кладется в базу, также создается event на проверку решения. `CheckerService` клонирует репозиторий, `mount`ит эту папку в новый докер-контейнер и запускает проверялку.
```

2022-06-18 18:54 UTC, maxuh14 commented on description/ARCHITECTURE.md
> +![Class diagram](diagrams/img/class-diagram.drawio.svg)
исправил

2022-06-18 19:34 UTC, maxuh14 commented on description/ARCHITECTURE.md
> +# Описание системы
Написал

2022-06-18 19:46 UTC, maxuh14 commented on description/ARCHITECTURE.md
> +  - `submissions/view`. Просмотреть все. Возвращает список всех попыток.
Поправил

2022-06-18 19:47 UTC, maxuh14 commented on description/ARCHITECTURE.md
> +  - `/teacher/uploadChecker`. Позволяет загрузить чекер преподу. Тело: json, представлюящим Dockerfile. Этот Dockerfile вместе с генерированным название кладется в базу, и создается event на создание
Поправил

2022-06-22 00:51 UTC, maxuh14 commented
@yurii-litvinov fixed

2022-06-24 12:20 UTC, yurii-litvinov approved these changes
В целом теперь ок. Зачтена.

2022-06-24 12:20 UTC, yurii-litvinov commented on description/ARCHITECTURE.md
> +    - `GET /tasks/?id={taskId}`. Возвращает детальную информацию о задании с номером `taskId`.
Просто `GET /tasks/{taskId}`. Задача — это ресурс, идентифицируемый в коллекции по номеру. id — это не дополнительный параметр, поэтому его не надо через `?`.

2022-06-24 12:31 UTC, closed without merging