HW12: Hwproj implementation
kibrq/sd-practice pull request #38
Opened 2022-05-23 20:58 UTC by maxuh14

Выполнили:
Суходольский Максим
Бриллиантов Кирилл
Салькаев Руслан

2022-06-16 16:32 UTC, yurii-litvinov requested changes
Очень технологично (однозначно +балл за "красивую вёрстку" и вообще), но не работает:
```
kibrq-sd-practice-build-1     | bash: ./gradlew: /bin/sh^M: bad interpreter: No such file or directory
kibrq-sd-practice-build-1 exited with code 126
kibrq-sd-practice-runner-1    | /usr/bin/env: 'bash\r': No such file or directory
kibrq-sd-practice-api-1       | /usr/bin/env: bash
: No such file or directory
kibrq-sd-practice-runner-1 exited with code 127
kibrq-sd-practice-api-1 exited with code 127
```
Запускал под виндой, но докер-образам должно быть всё равно по идее. Попробуйте починить запуск из docker compose под виндой. БД, RabbitMQ и UI стартанули нормально.

2022-06-16 16:32 UTC, yurii-litvinov commented on README.md
> +http://localhost:8080/swagger-ui.html
👍

2022-06-16 16:32 UTC, yurii-litvinov commented on api/src/main/kotlin/ru/hse/hwproj/api/controller/StudentController.kt
> +class StudentController(
Комментарии всё также нужны, у нас курс по архитектуре :)

2022-06-16 16:32 UTC, yurii-litvinov commented on api/src/main/kotlin/ru/hse/hwproj/api/controller/StudentController.kt
> +    @GetMapping("/submissions/all")
Как писал в комментариях к архитектуре, это не по REST-у, надо операции с ресурсами и коллекциями, а не методы в духе ООП типа GetAll()

2022-06-16 16:32 UTC, yurii-litvinov commented on api/src/main/kotlin/ru/hse/hwproj/api/security/WebSecurityConfig.kt
> +        source.registerCorsConfiguration("/**", configuration)
👍

2022-06-16 16:32 UTC, yurii-litvinov commented on runner/src/main/kotlin/ru/hse/hwproj/RunnerApplication.kt
> +    }
Так не надо, можно было раннером запускать ровно один чекер, зато много раннеров силами docker compose (через replicas). Это гибче и более идеологически правильно.

2022-06-16 16:32 UTC, yurii-litvinov commented on api/src/main/kotlin/ru/hse/hwproj/api/service/CheckerRequestsService.kt
> +class CheckerRequestsService(
Вообще, это против DDD, гексагональной архитектуры и т.п., сервисы знают про HTTP и про RabbitMQ напрямую, так что поменять средства доставки безболезненно будет нельзя. Ожидалась изолированная доменная модель, если по-хорошему.

2022-06-18 20:13 UTC, maxuh14 commented on api/src/main/kotlin/ru/hse/hwproj/api/controller/StudentController.kt
> +    @GetMapping("/submissions/all")
Изменил

2022-06-18 20:48 UTC, maxuh14 commented on runner/src/main/kotlin/ru/hse/hwproj/RunnerApplication.kt
> +    }
Сделал

2022-06-18 21:24 UTC, maxuh14 commented on api/src/main/kotlin/ru/hse/hwproj/api/service/CheckerRequestsService.kt
> +class CheckerRequestsService(
Вынес взаимодействие с RabbitMQ в другой класс, делая publish через интерфейс.
Глобально изменить архитектуру можно, но сейчас на это нет сил)

2022-06-18 22:20 UTC, maxuh14 commented on api/src/main/kotlin/ru/hse/hwproj/api/controller/StudentController.kt
> +class StudentController(
Добавил всюду.

2022-06-22 00:51 UTC, maxuh14 commented
> Очень технологично (однозначно +балл за "красивую вёрстку" и вообще), но не работает:
> 
> ```
> kibrq-sd-practice-build-1     | bash: ./gradlew: /bin/sh^M: bad interpreter: No such file or directory
> kibrq-sd-practice-build-1 exited with code 126
> kibrq-sd-practice-runner-1    | /usr/bin/env: 'bash\r': No such file or directory
> kibrq-sd-practice-api-1       | /usr/bin/env: bash
> : No such file or directory
> kibrq-sd-practice-runner-1 exited with code 127
> kibrq-sd-practice-api-1 exited with code 127
> ```
> 
> Запускал под виндой, но докер-образам должно быть всё равно по идее. Попробуйте починить запуск из docker compose под виндой. БД, RabbitMQ и UI стартанули нормально.

@yurii-litvinov
Починил.
Правда на винде не смог нормально передать pwd в докер. А нужен он для докера в докере: внутри контейнера используется прокинутый сокет докера, и пути для маунта папок относительно изначального хоста, а не контейнера, поэтому при запуске докера внутри нужно прибавлять префикс с абсолютным путем корня хоста.
На маке/линуксе можно прокинуть `$PWD` в переменную окружения, на винде получилось только с отдельной командой для записи pwd в `.env`.
Написал как запускать в ридми.

2022-06-24 15:17 UTC, yurii-litvinov approved these changes
Под виндой оно у меня так и не работает, но поскольку я не знаю почему, и на Linux всё в порядке, зачтена :)

2022-06-24 19:45 UTC, closed without merging